data:
  type: nlpcc
  base_path: 'data/'
  line_fname: 'train.seg'
  word_emb: 'word_emb'
  processed_path: 'processed_nlpcc_data'

  word_threshold: 2
  oov_threshold: 10
  max_seq_length: 100
  sentence_diff: 0.8
  testset_size: 1000

  PAD_ID: 0
  UNK_ID: 1
  START_ID: 2
  EOS_ID: 3

model:
  batch_size: 10
  num_layers: 2
  num_units: 128
  embed_dim: 128
  embed_share: true
  cell_type: gru
  dropout: 0.2
  encoder_type: bi
  attention_mechanism: normed_bahdanau
  attention_size: 128

train:
  epoch: 100
  size: 10000
  learning_rate: 0.001
  sampling_probability: 0.4
  dropout: 0.2

  train_steps: 1000
  model_dir: 'logs/hran'

  save_checkpoints_steps: 100000
  loss_hook_n_iter: 100
  check_hook_n_iter: 1000
  min_eval_frequency: 1000

  print_verbose: True
  debug: False

predict:
  beam_width: 10
  length_penalty_weight: 1.0

slack:
  webhook_url: ""
